### ISSUE TITLE
UX: Add time ranges to afternoon/evening (e.g. 11am-3pm) 

### ISSUE THREAD

**Issue by vanessia** [bocoup/blocks-capacity-planner#12]

**Comment by boazsender** [comment]
Here's what frontlinefoods currently does: ![image](https://user-images.githubusercontent.com/122117/80162693-db544180-8588-11ea-9f16-78d16202583b.png)

**Comment by vanessia** [comment]
yes! that's the one

**Comment by vanessia** [comment]
But what about the times in between? e.g. lots of deliveries happen between 1pm-7pm
@susanpark

**Comment by arebe** [comment]
Moving to meal names & time slots to match #15 per discussion in `#proj-backline-deliveries-planning`

Also, i'm going to tackle this issue :)

**Comment by rmeritz** [comment]
This is the 3rd duplicate.
