### ISSUE TITLE
Add morning + late night support to block

### ISSUE THREAD

**Issue by stivona** [bocoup/blocks-capacity-planner#24]
Adding morning + late night as time slots in the block in addition to afternoon + evening

Proposed time slots:
Morning (5:00 AM-12:00 PM) 
Afternoon (12:01 PM-5:00 PM)
Evening (5:01 PM-9:00 PM)
Late night (9:01 PM-1:00 AM)

**Comment by rmeritz** [comment]
This duplicates: https://github.com/bocoup/blocks-capacity-planner/issues/15

**Comment by rmeritz** [comment]
Closing because is a duplicate.
