### ISSUE TITLE
Update copy on the planning page to make it easier for people to use the tool

### ISSUE THREAD

**Issue by jesarshah** [bocoup/blocks-capacity-planner#40]
Add the following text: 

TITLE
"Plan your deliveries for the week" 

SUPPORTING TEXT
"Set the dates and budget, then the restaurants and hospitals will show up below. 
Drag the restauarnt card from the left column to the hospital section on the right to set a delivery." 

Alignment: center 

Copy changes on the planning portion of the block:

- Rename "unassigned" to "Ready to Deliver Restaurants"
- Add overarching text on the hospitals side "Recipients" (above name, time, fulfillment)
- Add label "Amount" above the amount column
- Rename restaurant shifts from "Monday evening" --> "Monday dinner" and "Sunday afternoon" --> "Sunday Lunch". @boazsender is this I could just make in the airtable base where these global variables are set?
- [discuss] @susanpark in the designs I see that the time has been taken out, but I think that is helpful for chapters when they're planning so we should have that in.

Image attached for reference
![image](https://user-images.githubusercontent.com/7271877/82084492-39fc6f00-96a0-11ea-9155-0b53b3f46d40.png)

**Comment by rmeritz** [comment]
It looks like this work is already being done in the PR: https://github.com/bocoup/blocks-capacity-planner/pull/47/files Which closes issue: #43

**Comment by arebe** [comment]
I believe this issue is for the copy on the rest of the block. #43 is just the schedule constraints portion.

**Comment by rmeritz** [comment]
> I believe this issue is for the copy on the rest of the block. #43 is just the schedule constraints portion.

@arebe - Ah, I see your existing work only covered some of these changes. I can take care of the rest.
